branch-defaults:
  production:
    environment: dj-prod
    group_suffix: null
environment-defaults:
  django-env:
    branch: null
    repository: null
global:
  application_name: configure
  branch: null
  default_ec2_keyname: EC2Instance
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
